### PR TITLE
Remove "send me hate mail" presubmit message

### PR DESCRIPTION
**Pull request by danbeam**

### CODE REVIEW

**Comment by danbeam** [comment]
https://codereview.chromium.org/1281783005/

**Comment by anniesullie** [comment]
Would you mind using rietveld as outlined here:https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md

That way we can send patches through our CQ.

**Comment by qyearsley** [comment]
Patch was committed in https://codereview.chromium.org/1281783005/

**Comment by danbeam** [comment]
@qyearsley that was a commit to chrome, not catapult.  they both use rietveld.

**Comment by danbeam** [comment]
nvm, I think you meant: https://codereview.chromium.org/1273223003/

**Comment by qyearsley** [comment]
Thanks for the correction :-)

**Pull request closed without merging**
