### PR TITLE
Allow symlinks to tracing binaries

### PR DESCRIPTION
**Pull request by ndfred**
This is needed to update the brew formula for trace2html.

Before the fix:

```
$ ln -s tracing/bin/trace2html trace2html
$ ./trace2html
Traceback (most recent call last):
  File "./trace2html", line 13, in <module>
    from tracing_build import trace2html
ImportError: No module named tracing_build
```
After the fix:

```
$ ./trace2html
usage: trace2html <options> trace_file1 [trace_file2 ...]
trace2html: error: too few arguments
```

### CODE REVIEW

**Comment by anniesullie** [comment]
In addition to the CLA, we use rietveld code review tool as outlined in the [contributor's guide](https://github.com/catapult-project/catapult/blob/master/CONTRIBUTING.md) (see the part about `git cl upload`)

**Comment by ndfred** [comment]
Unfortunately I checked with our lawyers and I can't sign the CLA, closing the PR. Thanks for your quick comment @anniesullie!

**Comment by vjeux** [comment]
@annesullie: we opened the pr on rietveld a week and a half ago but it didn't receive any feedback: https://codereview.chromium.org/1957663002/ 

All our performance tools on React Native rely on this awesome project and are broken right now until we can solve this problem. It would be awesome to get it resolved! Thanks

**Comment by anniesullie** [comment]
@vjeux thanks for the pointer! I'd be happy to review/approve the CL, but has lstellyl signed the CLA?

**Comment by vjeux** [comment]
Yup, he should have signed it. I'm pinging him right now to double check

**Comment by lelandrichardson** [comment]
@anniesullie Yes, I have signed the CLA.

**Comment by anniesullie** [comment]
Great, thanks! After addressing the review comments, we can land the patch (usually done by checking the "Commit" box after reviewer gives an lgtm)

**Pull request closed without merging**
